org: jacas
app: pieski
service: flask-api

provider:
  name: aws
  region: eu-west-2
  runtime: python3.8
  profile: serverless
  environment:
    AWS_KEY: ${param:AWS_KEY}
    AWS_SECRET: ${param:AWS_SECRET}
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
          - 's3:ListBucket'
        Resource: "arn:aws:s3:::pieski"
      - Effect: "Allow"
        Action:
          - "s3:GetObject"
        Resource: "arn:aws:s3:::pieski"
      - Effect: "Allow"
        Action:
          - "s3:PutObject"
        Resource: "arn:aws:s3:::pieski"


plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  wsgi:
    app: app.app
    pythonBin: python3 # Some systems with Python3 may require this
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
